on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
#  push:
#   tags:
#     - '*'
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events
  #page_build:
  #release:
  #  types: # This configuration does not affect the page_build event above
  #  - created
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.generate_tag.outputs.name }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Generate tag name
        id: generate_tag
        run: echo "::set-output name=name::v$(date -d "$(git show -s --format=%ci)" +'%Y.%-m.%-d')"
  build:
    name: build-fortiadc-ingress
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tagging
        run: | 
          git config user.name "ytlai"
          git config user.email lynn22414@gmail.com
          git tag "${{ needs.tag.outputs.name }}" -m "Version:${{ needs.tag.outputs.name }}"
      - name: create-templates-zip
        run: zip -r ./fad_ingress_helm_repo.zip ./*
      - name: upload-templates-zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ./fad_ingress_helm_repo.zip
          asset_name: fortiadc-ingress.zip
          tag: ${{needs.tag.outputs.name}}
          overwrite: true
          body: "FortiADC Ingress Release"
