on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
#   tags:
#     - '*'
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events
  #page_build:
  #release:
  #  types: # This configuration does not affect the page_build event above
  #  - created
jobs:
  build:
    name: build-fortiadc-ingress 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jacopocarlini/action-autotag@2.0.4
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          tag_prefix: "v"
#- uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: create-templates-zip
        run: zip -r ./fad_ingress_helm_repo.zip ./*
      - name: upload-templates-zip
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: ./fad_ingress_helm_repo.zip
          asset_name: fortiadc-ingress.zip
          tag: ${{steps.tagName.outputs.tagname}}
          overwrite: true
          body: "FortiADC Ingress Release"
