on:
  push:
   tags:
     - '*'
jobs:
  build:
    name: build-fortiadc-ingress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create release package
        run: tar zcvf ./fortiadc-ingress.tar.gz ./*
      - name: upload release package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          release_name: Release ${{needs.tag.outputs.name}}
          file: ./fortiadc-ingress.tar.gz
          asset_name: fortiadc-ingress.tar.gz
          tag: ${{github.ref}}
          overwrite: true
          body: "FortiADC Ingress Release"
